#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: bbdd
  become: true

  roles:
    -  geerlingguy.docker
    