---
- hosts: bbdd
  become: true

  tasks:

    - name: Copy file with owner and repo permissions
      copy:
        src: ./mongodb-org-5.0.repo
        dest: /etc/yum.repos.d/

    - name: Install mongodb
      yum:
        name: mongodb-org
        state: present
      notify:
        - start mongo


  handlers:

    - name: start mongo
      service:
        name: mongod
        state: started
        